### ISSUE TITLE
Make findclaim only give you one version of a module

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#110]
Maybe some like it the way it is, but I would prefer if "findclaim" only gave you one instance of the module, so you don't have people hording a whole bunch of the same module.

**Comment by elias5891** [comment]
Would prefer this as an option instead of a set usage -- I personally prefer being able to !findclaim wire and get all wire related modules, for example.

**Comment by CaitSith2** [comment]
Sorted out the optional part of this issue in 8563695d87662911ed6ab6c3df7a07fd60c8cb60

Now, !findclaim returns exactly one item for each search term, and !findclaimall returns everything.
