### ISSUE TITLE
Many newer modules have default point settings

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#120]
In particular Skyrim only gives out 5 points.  That's a crime, man.

**Comment by red031000** [comment]
This issue is invalid, the points for new modules are in componantsolverfactory.cs, however, if the default points are still in the file when componantsolverfactory.cs gets updated, they should be overridden by the value in componantsolverfactory.cs. They currently are not.

**Comment by red031000** [comment]
with the introduction of changing module scores in the chat, any scores that are not correct can be corrected in the chat. therefore I believe that this issue can be closed.
