### ISSUE TITLE
Limit the amount of module types one can do in a "findclaim" command

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#135]
Lately, I've seen people gobble up all their favorite modules using a "findclaimall <mod1>;<mod2>;<mod3>;etc..." command.  They've got it queued up in the beginning before the bomb is even shown.  Personally I think this is greedy and rude.  It also starts up a war of people competing with each other to do the same thing.  This can get out of hand.

I recommend that you limit the number of module types that can be findclaim'ed.  Also, I'd put a cooldown on repeated findclaim commands.  This way they'd have to share modules with others.

**Comment by red031000** [comment]
How many module types should someone be able to claim with one findclaimall command?

**Comment by rexkix** [comment]
That's a very good question.  I'm suggesting it be 2.  The most I'd think would be reasonable is 3.

**Comment by red031000** [comment]
partially addressed, the cooldown hasn't been implemented and any streamer settings also haven't been implemented

**Comment by Timwi** [comment]
I think this issue can be closed now? We have the claim limit and the cooldown period, which address all of the issues.

**Comment by rexkix** [comment]
With respect, I think this is a separate issue.  I find long strings of modules in a single "find claim" command at the beginning of a bomb to be annoying.

**Comment by samfun123** [comment]
What about a feature that allows users to specify which modules to claim at the beginning of the bomb?

**Comment by rexkix** [comment]
For instance, this user regularly does a findclaim command with 41 modules listed.  That's cwazy.  That's more modules than most bombs have.

https://cdn.discordapp.com/attachments/474726058428727298/514875180896616474/unknown.png

I'd say limit findclaim to 4 modules and that should be enough.  If you like, add a 30 second cooldown to subsequent findclaim commands.

**Comment by MrPeanut1028** [comment]
Resolved in #484
