### ISSUE TITLE
Timemode appears to be broken

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#140]
Timemode doesn't add time add when modules are solved.  I think this happened when the module IDs changed from numbers to letters.

**Comment by red031000** [comment]
this is invalid: time mode functions as normal, and adds time when modules are solved.

**Comment by red031000** [comment]
timemode is working as intended, the bug was caused by loading timemode while the bomb was loading. perhaps it's appropriate to consider a safeguard for this?

**Comment by rexkix** [comment]
I would think so.  I'd call it a bug, just not the bug I thought it was.

**Comment by rexkix** [comment]
Closed and a new issue has been raised that has a better title: "If you start a bomb in Normal Mode, then, before it's started immediately switch to Time Mode..."
