### ISSUE TITLE
unable to force solve module under specific circumstances

### ISSUE THREAD

**Issue by red031000** [samfun123/KtaneTwitchPlays#172]
if a command that relies on a certain time is executed, for example the button "release" command, a module cannot be force solved while that command is executing, this is not very useful if a module is bugged and continues waiting forever.

**Comment by samfun123** [comment]
I haven't run into a scenario where a module get stuck running forever but wouldn't `!stop` or `!cancel` stop the running coroutine? The module should be able to solved after that.

Maybe we should look into bypassing the module command execution and forcible stop execution and solve a module when a `!id solve` command is used.

**Comment by MrPeanut1028** [comment]
I believe this issue has now been fixed, as if you run `!# solve` a second time, the module is forced into a solved state.
