### ISSUE TITLE
mod crashes the game

### ISSUE THREAD

**Issue by alexvermaning0** [samfun123/KtaneTwitchPlays#249]
Version: 1

Gameversion: 1.3.0

Log: https://pastebin.com/Vj1BJLYA

**Comment by CaitSith2** [comment]
And Game version 1.3.0 is not actually supported by Twitch plays anymore.  You need to be running the latest version, which you can get either by opting out of all beta programs on steam,  or by grabbing from your humble bundle purchase page in case of the DRM free version.
