### ISSUE TITLE
!resetuser command doesn't work

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#274]
The !resetuser command doesn't work.  It says it does, but it doesn't do anything.

**Comment by red031000** [comment]
I can't replicate this

is there a specific instance where this didn't work? that might help me find if a certain user breaks it

**Comment by rexkix** [comment]
It always behaves this way for me.  See this image: https://cdn.discordapp.com/attachments/474726058428727298/509844521308258324/unknown.png

**Comment by red031000** [comment]
This seems to be an issue with cases, I'll try to fix this as soon as I can
