### ISSUE TITLE
Murder gave me a strike when it shouldn't have done so:

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#275]
I entered the right answer to Murder.  It said so in the log file.  It told me to raise it as an issue, so I'm doing that.

My data entry:
https://cdn.discordapp.com/attachments/239957935785115648/510318132338884618/unknown.png
It tells me to raise it as an issue:
https://cdn.discordapp.com/attachments/239957935785115648/510318566927499264/unknown.png

Log file view:
https://cdn.discordapp.com/attachments/239957935785115648/510318192048996363/unknown.png

Log file: 
https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=44e2bccbeb57366d5c2e83263cf09ee3998b2b0b;bomb=422ZB4

**Comment by samfun123** [comment]
This should be fixed now that #276 is merged in.
