### ISSUE TITLE
Make there be "!version" command for TP version info

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#299]
Make there be a "!version" or "!builddate" command so that people can easily see if the the TP build they're using is the latest.  "!version" would require version numbering and stuff, which could be annoying, but "!builddate" could just be the date of the last change to the build.

**Comment by red031000** [comment]
this might be an interesting thing to possibly add to the asset bundler? we could make it be able to set a date, if that's even possible, though that would probably require some reflection and some code on the unity side of things

**Comment by red031000** [comment]
or we could just assume that the build of the dll is the date of the update, that'd probably be easier

**Comment by samfun123** [comment]
Apparently it's possible to get the actual build date from the assembly. I found some info here: https://intellitect.com/displaying-deploymentbuild-date-web-pages/

**Comment by red031000** [comment]
yes, that's possible
