### ISSUE TITLE
Increase the strike limit for normal mode bombs

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#300]
Part of the reason people are doing Time Mode bombs pretty much exclusively is that Normal Mode bombs have a very strict limit on strikes.  The modules are also harder than they were in the day when people played more Normal Mode bombs.  Maybe Normal Mode would be more fun if the strike limit were increased.

I have no idea what the current strike limits are or how much they should be increased, but I could offer some suggestions if I had more information.

**Comment by samfun123** [comment]
The current code to calculate the number of strikes is: `Math.Max(3, modules / 12)`. Keep in mind that is division is integer division so you would need at least 48 modules to get 4 strikes not 47.

**Comment by rexkix** [comment]
Drake said it should be based on (modules / 6) and Sean said (modules / 8).  I keep looking for somebody else to get an opinion from, but that's been a difficult thing to find lately.  I don't do TP as much as I used to.  You might make it (modules / 8) or wait until I can find another opinion I trust.  Frankly, I'd recommend waiting.
