### ISSUE TITLE
Fix bug where commands get “stuck” in the queue and can’t be fixed with commands

### ISSUE THREAD

**Issue by ryaninator81** [samfun123/KtaneTwitchPlays#314]
On my twitch plays channel, certain commands get stuck in the queue, usually !run commands after a bomb. It requires manually clicking the continue/back button to fix, and then it executes the commands all at once, which can cause more problems.

**Comment by ryaninator81** [comment]
[output_log (3).txt](https://github.com/samfun123/KtaneTwitchPlays/files/2688821/output_log.3.txt)

This is a log from one of the incidents. I have the latest version (just in case it's an old log, however the error still happens)

**Comment by red031000** [comment]
this appears to happen when running a mission when the binder is being held, perhaps drop the binder first?

**Comment by samfun123** [comment]
I can't replicate this issue, I tried doing `!run 5 vanilla` in the post game screen and it worked normally.

**Comment by red031000** [comment]
The post game screen is not the issue, the bug happens when the binder in the setup room is being held

**Comment by samfun123** [comment]
I still can't replicate the issue, I held the binder and ran `!run 5 vanilla` without any problems.

**Comment by ryaninator81** [comment]
The commands I’m talking about are !run (mission ID) from mods or higher

**Comment by ryaninator81** [comment]
And it’s the post game screen

**Comment by samfun123** [comment]
Fixed by b119c90a4e87b0b5ab893ecac32eac487fe6a3ae
