### ISSUE TITLE
add TP to the steam workshop

### ISSUE THREAD

**Issue by red031000** [samfun123/KtaneTwitchPlays#338]
TP could get a lot more exposure by being on the steam workshop, this also makes it easier for streamers to get the latest version, at the potential cost of not be updated for every change on the github repo

**Comment by red031000** [comment]
I'm willing to upload it under my account, the checkforupdate and update commands would have to be disabled of course

**Comment by samfun123** [comment]
I don't know what to do about putting on the workshop, I personally like being able to push out updates very easily just using Dropbox so I don't know if I'd want to manage that. If you are willing to keep the workshop version updated then you can upload it. I'm not sure how we would detect if we are running from the workshop and disable those commands or if it's even necessary. Would Steam try to roll back to the Steam version if you updated to the Dropbox version?

**Comment by red031000** [comment]
it wouldn't try to roll it back, but when an update is pushed it would overwrite the changed files, so it may just not be even necessary to disable the command

**Comment by samfun123** [comment]
Something that might get confusing is that TP tells you if there is an update but there might not be an update on Steam but there is on Dropbox. Or if Steam updated after you did an update on Dropbox it might look like there was a regression.

**Comment by red031000** [comment]
true, I could just remove the commands for the steam build then
