### ISSUE TITLE
Camera-wall is completely broken

### ISSUE THREAD

**Issue by ryaninator81** [samfun123/KtaneTwitchPlays#344]
Camera wall does not auto-disable, and shows the back of modules instead of the front sometimes. It also doesn’t allow !x zoom to work, and doesn’t auto-fill with modules.

**Comment by samfun123** [comment]
I tried to test everything besides the auto-disable not working and everything worked fine for me. I ran a bomb with 18 modules, viewed them, enabled the camera wall using `!enablecamerawall` and then tried zooming one of them. Anything I should be doing differently? Are there any specific modules you noticed that have the issue? Are you on the latest build?

**Comment by ryaninator81** [comment]
I’ll attach some pictures soon

**Comment by ryaninator81** [comment]
![screen shot 2019-03-03 at 8 00 29 am](https://user-images.githubusercontent.com/45949859/53920840-5411da80-4023-11e9-9c37-8d6da04734bb.png)
This, and no modules auto-view

**Comment by ryaninator81** [comment]
Some modules, like The Jukebox, just don't view at all

**Comment by red031000** [comment]
this may be worth re-opening, since the bug is interactive mode specific and still exists

**Comment by ryaninator81** [comment]
I made a new one clarifying the issue
