### ISSUE TITLE
Grab point values from ktane.timwi.de

### ISSUE THREAD

**Issue by samfun123** [samfun123/KtaneTwitchPlays#368]
We would just need to grab them from the https://ktane.timwi.de/json/raw

**Comment by MrPeanut1028** [comment]
This could probably be changed to have the website now go off of the spreadsheet now that TP functions off of the spreadsheet.

**Comment by samfun123** [comment]
Yeah, I'm going to close this issue but I do really need to get around to getting the website to read the spreadsheet.
