### ISSUE TITLE
Command queue feature

### ISSUE THREAD

**Issue by Timwi** [samfun123/KtaneTwitchPlays#373]
Suggestion to add the following commands:

* `!q !5 submit 47` — Places the command `!5 submit 47` in the queue, to be executed when the queue operator makes a call.
* `!q 12 solves !5 submit 47` — Places the command `!5 submit 47` in the queue and gives it a name. Here, “12 solves” is the name, showing by example how the name can be used to indicate to the queue operator that this requires a specific number of solves. The name could be used for other purposes, too.
* `!call` — Runs the next queued-up command that doesn’t have a name. The system would then automatically execute the command; the solver no longer needs to be pinged or in any way involved; they already provided the command and it just runs.
* `!call 12 solves` — Runs the queued-up command with that name.

Whenever anything is in the solve queue, the Notes4 window would be replaced with something showing the state of the queue. It would list all the *named* items and the *number* of unnamed items.

The `!call` command could be restricted to players who have a claim on a specific set of modules (Forget Everything, Cookie Jars, etc.). This list of modules should be configurable via a setting.

A few extra commands could also be introduced. The only one I can think of right now would be `!unq`:
* `!unq` or `!unqall` — Removes all of your commands from the solve queue
* `!unq !5` — Removes your commands for that module
* `!unq 12 solves` — Removes a named command

Furthermore, moderators should have the ability to remove someone else’s command from the queue.

One issue is what to call this. The feature is intended to enhance a player convention currently referred to as a “solve queue”; however, the proposed feature does not really deal with solves, but can be used with any commands (and it should; some commands are a “maybe solve”, e.g. when you don’t know how many stages a module will have; some modules are special like Fast Math etc.). So calling it “solve queue” is technically wrong, but “command queue” already refers to something (the queue of commands actually submitted but yet to be executed).

**Comment by Timwi** [comment]
I have begun work on this.

**Comment by MrPeanut1028** [comment]
Added in #375
