### ISSUE TITLE
Add help commands for the new stuff like !q and !call

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#381]
Please add help commands for !q and !call and other related new commands.

I think that !q help should list all the related commands as well as explain how to use the !q command.  That way people would know what the these other commands.  As it is, I don't think people will remember the command to delete a command from the queue, for example.

Of course the !q command shouldn't explain how to use the !unq command, it should just list it and say that it exists.  Say something like: "Related commands: unq, call".

**Comment by samfun123** [comment]
Maybe we should have a !help command that gives you help on various different topics. Not sure which way would be better.

**Comment by samfun123** [comment]
Closed by be1a67db45585d12bb12e935b5bc5c6043f926d4
