### ISSUE TITLE
Echo the command executed when the !call is done in the chat

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#386]
Please echo the command that is executed when a !call is done to the chat.
Commands are either going to:
a) solve the module
b) give a strike
c) complain about being incorrect or formatted wrongly

In the case of b) or especially c) you'd want to know what you did so you can fix it.
For instance, if the module is minesweeper, you might say:

!q !13 flag 4 3, 5 2, 6 2

(i.e. you use "," instead of ";")
(or maybe you leave out a semicolon that you meant to add.)

The module simply says that you did something wrong.  How are you supposed to know what happened?

**Comment by samfun123** [comment]
Closed by d7a65d56fedebb9d98256d0d34e45a736e377127
