### ISSUE TITLE
Consider automatically lower-casing commands

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#42]
Some modules incorrectly accept only commands in lower case.  At the risk of breaking future modules which could depend on case (which is a bad idea, IMO), lower case all commands (and arguments) for modules so they can't make that mistake.

**Comment by MrPeanut1028** [comment]
Hate to say it, but a few modules use Case-sensitivity now. Double Arrows comes to mind. Besides, modules do this locally now if necessary.

**Comment by samfun123** [comment]
Modules should definitely strive to be case-insensitive but I don't think I'm going to break the API by making all commands lower-case.
