### ISSUE TITLE
Password available for chat?

### ISSUE THREAD

**Issue by Fantomita** [samfun123/KtaneTwitchPlays#425]
I can't find a setting to make the password module available for chat.
Can you help me?

**Comment by red031000** [comment]
I'm not sure what you mean by "available for chat", could you clarify?

**Comment by Fantomita** [comment]
Well... the password module says confidential and no one besides me (from the game) can interract with it

**Comment by red031000** [comment]
what version of the game are you using, and where did you get it from?

**Comment by Fantomita** [comment]
I am using the 1.8.3 version and I got it from igg games but I am planning to buy the game in like a week or so

**Comment by red031000** [comment]
TP is not compatible with 1.8.3, please buy the game and use the latest version

**Comment by Fantomita** [comment]
oh... that's the problem?

**Comment by Fantomita** [comment]
but... it is working just fine. the only problem is that the password module says confidential

**Comment by red031000** [comment]
the code has been changed to reflect the latest version of the game, there may be other issues since the current code hasn't been tested with an earlier version

**Comment by Fantomita** [comment]
oh ok thanks
