### ISSUE TITLE
Allow for multiple people to use !call for a solve

### ISSUE THREAD

**Issue by MrPeanut1028** [samfun123/KtaneTwitchPlays#462]
Mission bombs often have multiple people on bosses, so have a command such as `!callset #` to require multiple uses of !call in order to send one of the queued commands, and could be overridden with `!callnow` or `!callallnow` similarly.

**Comment by MrPeanut1028** [comment]
#466 Added here

**Comment by KingBranBran** [comment]
@MrPeanut1028 Do you want to use #467 ? It has the !callnow command with it.

**Comment by MrPeanut1028** [comment]
Yeah, yours will probably work better, and it looks a lot neater. Shame that we made these on the same day. Thanks!
