### ISSUE TITLE
More flexible un-queue commands.

### ISSUE THREAD

**Issue by sleepin-fang** [samfun123/KtaneTwitchPlays#463]
Given the only way to unqueue a queued command is with !unq !#, it might be useful to have !unqall to unqueue all queued modules (claimed by a user) and !unq <name> for unqueuing named modules

**Comment by sleepin-fang** [comment]
just noticed the !unqall and !unq <name> is on the commands list but it doesn't work
(except !unqall works for mods

**Comment by KingBranBran** [comment]
Maybe !unqall could be for everyone and it only removes their modules from the queue. The !delq will be for mods that need to delete the queue.
