### ISSUE TITLE
!callset improvements

### ISSUE THREAD

**Issue by MrPeanut1028** [samfun123/KtaneTwitchPlays#469]
As of now, only `!call` is counted when doing a greater than 1 callset. This should be changed to include other calls in general. Also, a command (perhaps `!callcount`) could be made to see how many people have used any type of call. Lastly, a line should be added that says "2 of 2 calls reached, calling command." or something of the sort. 

I fully intent to do this later in the week, but I'd like other ideas and suggestions for the system.

**Comment by KingBranBran** [comment]
What would be the best way to implement the other !call methods?

Let's say we had a module (13) that needs to be called on "5 solves". Would everyone need to do !call "5 solves". Or only the last person in the call?

Also, do you think that it would be cool to restrict a call to a single person, so two different people have to call and eliminates someone accidentally doing two calls?

**Comment by sleepin-fang** [comment]
Imo, if the `callset` is greater than 1, then either a line added that says `Required calls reached, calling the next queued command`, or replace the call command to be `Required calls reached, calling <username>: <command>`.

Also, the calls should be only called once by same person, in case the person forgot if they did `!call` already (not sure if that's a thing already, I didn't have a chance to test it).

**Comment by KingBranBran** [comment]
>Also, the calls should be only called once by same person, in case the person forgot if they did !call already (not sure if that's a thing already, I didn't have a chance to test it).

Yea we haven't implemented this yet.

**Comment by MrPeanut1028** [comment]
I think that having a preventative feature to stop double-calling is a good idea, and it would probably be simple (storing names in an array, checking if they already called, adding if they haven't already). I think adding a reasonable cap to this would work, probably 10 just for fun. 

Also, the last person to call would be the person that would specify if it was a named command. The others could do `!call literally anything` and it would count is as a call that is needed.

**Comment by KingBranBran** [comment]
I mean, I have done multiple missions where there have been 30 + boss modules, so I don't know if we should keep the limit too low. Maybe something very unnecessary like over 50 modules.

**Comment by MrPeanut1028** [comment]
I'm fine with that, although I have only ever had 24 people talk in my chat at once, so it seems almost impossible lol

**Comment by sleepin-fang** [comment]
I personally think that setting the cap too high (like 10 or more) isn't a good idea, since trolls exist.

Also another idea for minor thing - adding/replacing message when `!callnow` is used (when `callset` is higher than 1), either adding message like `Bypassing required number of calls, calling the next queued command`, or replacing the call message to `Bypassing the required number of calls, calling <username>: <command>`.
