### ISSUE TITLE
Strike message explaination

### ISSUE THREAD

**Issue by sleepin-fang** [samfun123/KtaneTwitchPlays#476]
Strike message explaining what successful command had been executed before the module strikes / explaining which particular command gave the strike.

(I've only seen Wire Sequences doing that, but not for other modules.

**Comment by samfun123** [comment]
This is usually only done in cases where it's not clear what happened when watching the command execute and has to be done manually by the implementer. I'd probably want to get some opinions from the community before including the last command in the strike message whenever a command strikes.

**Comment by sleepin-fang** [comment]
There're several modules which becomes impossible to determine what input gave a strike (e.g. Double Arrows - 10 inputs, strikes if one is wrong) other than reset.

**Comment by samfun123** [comment]
Well those modules can use the `strikemessage <message>` API to let the user know why they were given a strike.

**Comment by samfun123** [comment]
I'm closing this issue because I've described a way for this problem to be fixed by modules. If there is still an issue, let me know.
