### ISSUE TITLE
consider using a proper release system

### ISSUE THREAD

**Issue by red031000** [samfun123/KtaneTwitchPlays#478]
this one isn't really about an issue with the code, but it's more about the project as a whole

rather than having a system where code can be potentially buggy, with no way back to an earlier build without re-compiling or getting one from someone else, so an emergency fix is required to make it us-able, consider having a system where we have stable/alpha/beta releases, especially since TP is growing, and we're getting a lot more contributors now

I know I haven't exactly been contributing that much anymore, but it'd be useful to also introduce versioning, so we can take advantage of the github tags and releases system, and not have to use dropbox anymore, it'd potentially also be useful to have the steam build (when that comes online after the issue with translated modules is resolved) to host the latest stable build

**Comment by samfun123** [comment]
The thing I don't like about this suggested release system this is that it adds additional steps to something that is currently very easy. So if I was going to switch to that release system it would need to have some benefits to out weight that. One benefit is that this system could allow for reverting, but we could also implement something like that in the current system by keeping around the last build. I might just be missing something but I don't see what other benefits there are to using this suggested system.

**Comment by red031000** [comment]
there are cases where the latest build has had some potentially untested code in it, since some PRs aren't tested as much as they should be, and as such an "alpha" or "beta" is released as the latest build, and if something ends up breaking, then you can't revert back to a known good build without someone providing that

**Comment by samfun123** [comment]
I did address that flaw of the current system:
> we could also implement something like that in the current system by keeping around the last build
