### ISSUE TITLE
近期蓝灯无法使用

### ISSUE THREAD

**Issue by ilove111** [samfun123/KtaneTwitchPlays#485]
近期付费专业版蓝灯无法使用

**Comment by samfun123** [comment]
Sorry, I don't speak Chinese. So I've translated your message and this message with Google Translate. According to Google Translate you said "Blue light is unavailable." I don't know what that means. Could you clarify what you mean? Or if you speak English, writing your messages in English would be easier for me.

对不起，我不会说中文。 因此，我已使用Google翻译翻译了您的消息和此消息。 根据Google翻译的说法，“蓝灯不可用”。 我不知道那是什么意思 您能说明您的意思吗？ 或者，如果您会说英语，对我来说，用英语写消息会更容易。

**Comment by ilove111** [comment]
The lantern of the professional version is not available recently


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sam"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 上午10:54
收件人:&nbsp;"samfun123/KtaneTwitchPlays"<KtaneTwitchPlays@noreply.github.com&gt;;
抄送:&nbsp;"ilove"<594497261@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [samfun123/KtaneTwitchPlays] 近期蓝灯无法使用 (#485)




Sorry, I don't speak Chinese. So I've translated your message and this message with Google Translate. According to Google Translate you said "Blue light is unavailable." I don't know what that means. Could you clarify what you mean? Or if you speak English, writing your messages in English would be easier for me.
 
对不起，我不会说中文。 因此，我已使用Google翻译翻译了您的消息和此消息。 根据Google翻译的说法，“蓝灯不可用”。 我不知道那是什么意思 您能说明您的意思吗？ 或者，如果您会说英语，对我来说，用英语写消息会更容易。

**Comment by samfun123** [comment]
Sorry, I still don't know what you're talking about. This mod for the game Keep Talking and Nobody Explodes doesn't have any kind of professional version.

**Comment by samfun123** [comment]
Closing due to lack of information.
