### ISSUE TITLE
Allow alternative !find commands to find a specific module.

### ISSUE THREAD

**Issue by kavinkul** [samfun123/KtaneTwitchPlays#486]
Currently, !find command lists up to 3 of every module that contains the word the player specified which could make it difficult for player to find certain modules that are required to be solved at that time such as V when it appears on organization or Keypad when there is turn the keys (as there can be a lot of modules with their names containing keypad on that same bomb). Adding a command like !findexact <Exact module name> or !findbyID <moduleID> would allow player to find such modules more easily.

**Comment by samfun123** [comment]
If you type the full name of the module into the command (`!find V`), it will be sorted before other modules in the listing. I'm closing this as I believe this covers the suggestion.
