### ISSUE TITLE
Standardization: Forcing all scores to have 2 d.p. (keeping zeroes)

### ISSUE THREAD

**Issue by sleepin-fang** [samfun123/KtaneTwitchPlays#489]
What title said.

**Comment by MrPeanut1028** [comment]
Personally, I think keeping decimal places off of the leaderboard would be best.

**Comment by samfun123** [comment]
I've made it so the leaderboard displays trailing zeros. @MrPeanut1028 Try out the trailing zeros and let me know if you think we should remove the decimal places.
