### ISSUE TITLE
TP Attempted Autosolve

### ISSUE THREAD

**Issue by djm4556** [samfun123/KtaneTwitchPlays#492]
I built my free house and road, then erroneously tried to claim resources from the hexes that produce on the starting roll. It gave me a strike, then said to fill out an issue here regarding an attempted autosolve. Log will be provided once the bomb ends.

**Comment by MrPeanut1028** [comment]
If this is a bug regarding a specific module, please  contact the author. You can find them either on Steam or here in the Twitch Plays discord server: [https://discord.gg/CYVWy3n](https://discord.gg/CYVWy3n)
