### ISSUE TITLE
General Help on a web page

### ISSUE THREAD

**Issue by rexkix** [samfun123/KtaneTwitchPlays#52]
If somebody does a !help command, TP should respond with help for some of the most basic commands (e.g. !25 claim or !25 view), but it should also give a link to a web page that documents _all_ the general purpose commands (e.g. !find, etc.)

As it stands, many commands like !find are only known by people in the know.  Others have to learn about them by watching them be used.  There should be a place where people can learn about all the commands that are supported.

If it helps, I volunteer to help maintain this page.

**Comment by samfun123** [comment]
https://github.com/samfun123/KtaneTwitchPlays/wiki/Commands
