### ISSUE TITLE
update command list

### ISSUE THREAD

**Issue by red031000** [samfun123/KtaneTwitchPlays#96]
While this issue has been mostly resolved, there is still a lack of documentation concerning the ranked-user commands; they haven't been updated to reflect the changes in commands for mod+ and super-user+ users.

**Comment by red031000** [comment]
due to time, this has become an issue again, it may be a good idea to auto-generate some documentation, perhaps with xml comments?

**Comment by samfun123** [comment]
I hadn't thought of using XML comments. I went ahead and made an example of what it might look like. We also should probably write some C# code that would also output all the access levels. The escaping of the < and > for arguments in the example is a bit annoying but not too bad. The param tags aren't necessary but maybe we could figure out a way to generate the example using those. They could also be put under an expandable section for more information, like this:
<details>
   <summary>Arguments</summary>

   `targetPlayer` - The player who should get the points.
   `bonus` - The number of points for the user to get.
</details>

```csharp
/// <summary>
/// Adds bonus points to a target player.
/// </summary>
/// <param name="targetPlayer">The player who should get the points.</param>
/// <param name="bonus">The number of points for the user to get.</param>
/// <example>!bonusscore &lt;targetPlayer&gt; &lt;bonus&gt;</example>
[Command(@"bonus(?:score|points) (\S+) (-?[0-9]+)", AccessLevel.SuperUser, AccessLevel.SuperUser)]
public static void BonusPoints([Group(1)] string targetPlayer, [Group(2)] int bonus, string user)
{
	IRCConnection.SendMessageFormat(TwitchPlaySettings.data.GiveBonusPoints, targetPlayer, bonus, user);
	Leaderboard.Instance.AddScore(targetPlayer, new Color(.31f, .31f, .31f), bonus);
}
```

**Comment by samfun123** [comment]
I'm going to close this as the new command reference is out: https://samfun123.github.io/KtaneTwitchPlays/
